((lambda (true false and or not if-then-else write-true write-false test-1 test-2 test-3 test-4)
   ((lambda (result-1 result-2 result-3 result-4)
     (cons result-1 (cons result-2 (cons result-3 (cons result-4 null)))))
     (((test-1 true false and or) write-true write-false))
     (((test-2 true false and or) write-true write-false))
     (((test-3 true false and or) write-true write-false))
     (((test-4 true false and or) write-true write-false))))

  (lambda (t f) t)
  (lambda (t f) f)
  (lambda (p q) (p q p))
  (lambda (p q) (p p q))
  (lambda (p) (p (lambda (t f) f)
                 (lambda (t f) t)))
  (lambda (p a b) (p a b))
  (lambda () (quote true))
  (lambda () (quote false))
  (lambda (true false and or)
    (and true true))
  (lambda (true false and or)
    (and true false))
  (lambda (true false and or)
    (or true false))
  (lambda (true false and or)
    (or false false))
 )
